export const APP_PRODUCT_NAME = 'FairPlay';
export const APP_API_NAME = `${APP_PRODUCT_NAME} API`;
export const APP_VERSION = process.env.npm_package_version ?? '1.0.0';

export const EMAIL_MAX_LENGTH = 254;
export const USERNAME_MIN_LENGTH = 3;
export const USERNAME_MAX_LENGTH = 20;
export const DISPLAY_NAME_MAX_LENGTH = 30;
export const BIO_MAX_LENGTH = 200;
export const PASSWORD_MIN_LENGTH = 8;
export const PASSWORD_MAX_LENGTH = 128;

export const HOUR_MS = 1000 * 60 * 60;
export const DAYS_MS = 24 * HOUR_MS;
export const MINUTE_MS = 1000 * 60;

export const PASSWORD_RESET_CODE_TTL_MINUTES = 15;
export const EMAIL_VERIFICATION_CODE_TTL_MINUTES = 15;
export const PASSWORD_RESET_TOKEN_TTL_MS = PASSWORD_RESET_CODE_TTL_MINUTES * MINUTE_MS;
export const EMAIL_VERIFICATION_TOKEN_TTL_MS = EMAIL_VERIFICATION_CODE_TTL_MINUTES * MINUTE_MS;

export const SESSION_TTL_DAYS = 30;
export const SESSION_TTL_MS = SESSION_TTL_DAYS * DAYS_MS;
export const SESSION_IP_ADDRESS_MAX_LENGTH = 45;
export const SESSION_USER_AGENT_MAX_LENGTH = 512;
export const SESSION_DEVICE_INFO_MAX_LENGTH = 512;

export const SESSION_CLEANUP_INTERVAL_MINUTES = 60;
export const SESSION_CLEANUP_INACTIVE_RETENTION_DAYS = SESSION_TTL_DAYS;
export const SESSION_CLEANUP_INTERVAL_MS = SESSION_CLEANUP_INTERVAL_MINUTES * MINUTE_MS;
export const SESSION_CLEANUP_INACTIVE_RETENTION_MS =
  SESSION_CLEANUP_INACTIVE_RETENTION_DAYS * DAYS_MS;
export const AUTH_CLEANUP_LOCK_TTL_MS = 5 * MINUTE_MS;

export const DEFAULT_JSON_BODY_LIMIT_BYTES = 1024 * 1024;
export const DEFAULT_PROFILE_MEDIA_MAX_UPLOAD_BYTES = 3 * 1024 * 1024;
export const AVATAR_IMAGE_SIZE_PX = 512;
export const BANNER_IMAGE_WIDTH_PX = 1500;
export const BANNER_IMAGE_HEIGHT_PX = 500;
export const DEFAULT_OBJECT_STORAGE_BUCKET = 'fairplay-user-media';
export const DEFAULT_OBJECT_STORAGE_REGION = 'us-east-1';
export const DEFAULT_OBJECT_STORAGE_SIGNED_URL_TTL_SECONDS = 15 * 60;
export const DEFAULT_OBJECT_STORAGE_TIMEOUT_MS = 5_000;
export const DEFAULT_SMTP_TIMEOUT_MS = 10_000;
export const MAX_EXTERNAL_OPERATION_TIMEOUT_MS = 120_000;

export const PROFILE_MEDIA_UPLOAD_RATE_LIMIT_WINDOW_MS = 15 * MINUTE_MS;
export const PROFILE_MEDIA_UPLOAD_RATE_LIMIT_MAX = 10;

export const EXPENSIVE_AUTH_MUTATION_RATE_LIMIT_WINDOW_MS = 15 * MINUTE_MS;
export const EXPENSIVE_AUTH_MUTATION_RATE_LIMIT_MAX = 10;

export const REGISTRATION_IDENTIFIER_RATE_LIMIT_WINDOW_MS = HOUR_MS;
export const REGISTRATION_IDENTIFIER_RATE_LIMIT_MAX = 3;

export const LOGIN_IDENTIFIER_RATE_LIMIT_WINDOW_MS = 10 * MINUTE_MS;
export const LOGIN_IDENTIFIER_RATE_LIMIT_MAX = 5;

export const VERIFY_EMAIL_IDENTIFIER_RATE_LIMIT_WINDOW_MS = 10 * MINUTE_MS;
export const VERIFY_EMAIL_IDENTIFIER_RATE_LIMIT_MAX = 5;

export const PASSWORD_RESET_IDENTIFIER_RATE_LIMIT_WINDOW_MS = HOUR_MS;
export const PASSWORD_RESET_IDENTIFIER_RATE_LIMIT_MAX = 5;
export const PASSWORD_RESET_EMAIL_COOLDOWN_MS = 5 * MINUTE_MS;

export const RESET_PASSWORD_IDENTIFIER_RATE_LIMIT_WINDOW_MS = 10 * MINUTE_MS;
export const RESET_PASSWORD_IDENTIFIER_RATE_LIMIT_MAX = 5;

export const RESEND_VERIFICATION_IDENTIFIER_RATE_LIMIT_WINDOW_MS = HOUR_MS;
export const RESEND_VERIFICATION_IDENTIFIER_RATE_LIMIT_MAX = 5;
export const RESEND_VERIFICATION_EMAIL_COOLDOWN_MS = 2 * MINUTE_MS;
