export const APP_PRODUCT_NAME = 'FairPlay';
export const APP_API_NAME = `${APP_PRODUCT_NAME} API`;
export const EMAIL_VERIFICATION_PATH = '/verify-email';
export const PASSWORD_RESET_PATH = '/reset-password';
export const APP_VERSION = process.env.npm_package_version ?? '1.0.0';

export const EMAIL_MAX_LENGTH = 254;
export const USERNAME_MIN_LENGTH = 3;
export const USERNAME_MAX_LENGTH = 20;
export const DISPLAY_NAME_MAX_LENGTH = 30;
export const BIO_MAX_LENGTH = 200;
export const PASSWORD_MIN_LENGTH = 8;
export const PASSWORD_MAX_LENGTH = 128;

export const HOUR_MS = 1000 * 60 * 60;
export const DAYS_MS = 24 * HOUR_MS;
export const MINUTE_MS = 1000 * 60;

export const PASSWORD_RESET_TOKEN_TTL_DAYS = 1;
export const EMAIL_VERIFICATION_TOKEN_TTL_DAYS = 7;
export const PASSWORD_RESET_TOKEN_TTL_MS = PASSWORD_RESET_TOKEN_TTL_DAYS * DAYS_MS;
export const EMAIL_VERIFICATION_TOKEN_TTL_MS = EMAIL_VERIFICATION_TOKEN_TTL_DAYS * DAYS_MS;

export const SESSION_TTL_DAYS = 30;
export const SESSION_TTL_MS = SESSION_TTL_DAYS * DAYS_MS;

export const SESSION_CLEANUP_INTERVAL_MINUTES = 60;
export const SESSION_CLEANUP_INACTIVE_RETENTION_DAYS = SESSION_TTL_DAYS;
export const SESSION_CLEANUP_INTERVAL_MS = SESSION_CLEANUP_INTERVAL_MINUTES * MINUTE_MS;
export const SESSION_CLEANUP_INACTIVE_RETENTION_MS =
  SESSION_CLEANUP_INACTIVE_RETENTION_DAYS * DAYS_MS;
export const AUTH_CLEANUP_LOCK_TTL_MS = 5 * MINUTE_MS;

export const DEFAULT_JSON_BODY_LIMIT_BYTES = 1024 * 1024;

export const LOGIN_IDENTIFIER_RATE_LIMIT_WINDOW_MS = 10 * MINUTE_MS;
export const LOGIN_IDENTIFIER_RATE_LIMIT_MAX = 5;

export const PASSWORD_RESET_IDENTIFIER_RATE_LIMIT_WINDOW_MS = HOUR_MS;
export const PASSWORD_RESET_IDENTIFIER_RATE_LIMIT_MAX = 5;
export const PASSWORD_RESET_EMAIL_COOLDOWN_MS = 5 * MINUTE_MS;

export const RESEND_VERIFICATION_IDENTIFIER_RATE_LIMIT_WINDOW_MS = HOUR_MS;
export const RESEND_VERIFICATION_IDENTIFIER_RATE_LIMIT_MAX = 5;
export const RESEND_VERIFICATION_EMAIL_COOLDOWN_MS = 2 * MINUTE_MS;
